# docker-compose
version: '3'

services:
  # MySQL Database
  database:
    platform: linux/x86_64
    image: mariadb:10.3
    restart: 'no'
    ports:
      - '3306:3306'
    volumes:
      - ./mysqldata:/var/lib/mysql
    command: --lower_case_table_names=1 --explicit_defaults_for_timestamp=1 --innodb_use_native_aio=0
    environment:
      MARIADB_ROOT_PASSWORD: 'password'
      MARIADB_USER: 'shoot'
      MARIADB_PASSWORD: 'password'
      MARIADB_DATABASE: 'spacex'
      MARIADB_HOST: localhost

  # AWS Local
  localstack:
    image: localstack/localstack:0.14.3
    environment:
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localhost
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - AWS_DEFAULT_REGION=eu-west-1
      - DEFAULT_REGION=eu-west-1
      - EDGE_PORT=4566
      - SERVICES=s3
    hostname: localhost
    ports:
      - '4566:4566'
    volumes:
      - ./localstack/tmp:/tmp/localstack
      - ./init-aws:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock
